### Get /
GET http://localhost:3000

### Register test
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"
}

### Login test
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"
}