version: '3'
services:
  app: 
    build: .
    container_name: diary-be
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/diary
      - JWT_SECRET=my_jwt_key
      - NODE_ENV=development
      - PORT=5003
    ports:
      - "5003:5003"
    depends_on:
      - db
    volumes:
      - .:/app
  db: 
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=diary
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: