### Get /
GET http://localhost:5000

### Register test
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"
}

### Login test
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123123123"
}

### Fetch all diaries
GET http://localhost:5000/diaries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxNDIwMzk1LCJleHAiOjE3NDE1MDY3OTV9.QHyM5Tb7deCL4fCk7jrEdWGWWa_Wooclll1jvdljdrQ

### Update diary 
PUT http://localhost:5000/diaries/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxNDIwMzk1LCJleHAiOjE3NDE1MDY3OTV9.QHyM5Tb7deCL4fCk7jrEdWGWWa_Wooclll1jvdljdrQ

{
    "content": "bum bum bum bum"
}

### Create diary
POST http://localhost:5000/diaries
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxNDIwMzk1LCJleHAiOjE3NDE1MDY3OTV9.QHyM5Tb7deCL4fCk7jrEdWGWWa_Wooclll1jvdljdrQ

{
    "content": "haiajsdaj"
}